/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_VSR_VSR_PB_H_INCLUDED
#define PB_VSR_VSR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* High Level Motor State Enum */
typedef enum _vsr_MotorErrorState_MotorState {
    vsr_MotorErrorState_MotorState_MOTOR_OK = 0,
    vsr_MotorErrorState_MotorState_MOTOR_ERROR_STOP = 1
} vsr_MotorErrorState_MotorState;

/* Protection Code */
typedef enum _vsr_MotorSafety_ProtectionCode {
    vsr_MotorSafety_ProtectionCode_NO_PROTECTIONS_ACTIVE_0 = 0,
    vsr_MotorSafety_ProtectionCode_BATTERY_CURRENT_HIGH_6 = 6,
    vsr_MotorSafety_ProtectionCode_BATTERY_UNDERVOLTAGE_8 = 8,
    vsr_MotorSafety_ProtectionCode_BATTERY_VOLTAGE_TOO_HIGH_2 = 2,
    vsr_MotorSafety_ProtectionCode_DC_CAPACITOR_TEMPERATURE_HIGH_10 = 10,
    vsr_MotorSafety_ProtectionCode_FOC_CIRCLE_LIMIT_3 = 3,
    vsr_MotorSafety_ProtectionCode_HIGH_CURRENT_APPLIED_TOO_LONG_11 = 11,
    vsr_MotorSafety_ProtectionCode_INVERTER_TEMPERATURE_HIGH_5 = 5,
    vsr_MotorSafety_ProtectionCode_IQ_DECREASED_FIELD_WEAKENING_12 = 12,
    vsr_MotorSafety_ProtectionCode_MOTOR_STALL_7 = 7,
    vsr_MotorSafety_ProtectionCode_MOTOR_TEMPERATURE_HIGH_4 = 4,
    vsr_MotorSafety_ProtectionCode_UNUSED1_1 = 1,
    vsr_MotorSafety_ProtectionCode_UNUSED2_9 = 9
} vsr_MotorSafety_ProtectionCode;

/* Safety Error Code */
typedef enum _vsr_MotorSafety_SafetyErrorCode {
    vsr_MotorSafety_SafetyErrorCode_NO_ERROR_0 = 0,
    vsr_MotorSafety_SafetyErrorCode_BATTERY_VOLTAGE_TOO_LOW_22 = 22,
    vsr_MotorSafety_SafetyErrorCode_CAN_TIMEOUT_19 = 19,
    vsr_MotorSafety_SafetyErrorCode_EEPROM_COMMUNICATION_ISSUE_7 = 7,
    vsr_MotorSafety_SafetyErrorCode_EMERGENCY_SWITCH_PRESSED_32 = 32,
    vsr_MotorSafety_SafetyErrorCode_ENCODER_ANGLE_24 = 24,
    vsr_MotorSafety_SafetyErrorCode_FLUX_CURRENT_TOO_HIGH_23 = 23,
    vsr_MotorSafety_SafetyErrorCode_GATE_DRIVER_SUPPLY_VOLTAGE_18 = 18,
    vsr_MotorSafety_SafetyErrorCode_HS_FET_SHORT_CIRCUIT_13 = 13,
    vsr_MotorSafety_SafetyErrorCode_HS_L1_DRV_U24_CANT_TURN_ON_1 = 1,
    vsr_MotorSafety_SafetyErrorCode_HS_L2_DRV_U23_CANT_TURN_ON_2 = 2,
    vsr_MotorSafety_SafetyErrorCode_HS_L3_DRV_U22_CANT_TURN_ON_3 = 3,
    vsr_MotorSafety_SafetyErrorCode_HW_OVERVOLTAGE_31 = 31,
    vsr_MotorSafety_SafetyErrorCode_ID_OVERCURRENT_36 = 36,
    vsr_MotorSafety_SafetyErrorCode_IGBT_DESATURATION_26 = 26,
    vsr_MotorSafety_SafetyErrorCode_IGBT_TEMPERATURE_READ_30 = 30,
    vsr_MotorSafety_SafetyErrorCode_LS_FET_SHORT_CIRCUIT_14 = 14,
    vsr_MotorSafety_SafetyErrorCode_LS_L1_DRV_U24_CANT_TURN_ON_4 = 4,
    vsr_MotorSafety_SafetyErrorCode_LS_L2_DRV_U23_CANT_TURN_ON_5 = 5,
    vsr_MotorSafety_SafetyErrorCode_LS_L3_DRV_U22_CANT_TURN_ON_6 = 6,
    vsr_MotorSafety_SafetyErrorCode_MOTOR_STALL_LONGER_THAN_30_SECONDS_33 = 33,
    vsr_MotorSafety_SafetyErrorCode_NO_CAN_MESSAGES_25 = 25,
    vsr_MotorSafety_SafetyErrorCode_OFFSET_PHASE_A_15 = 15,
    vsr_MotorSafety_SafetyErrorCode_OFFSET_PHASE_B_16 = 16,
    vsr_MotorSafety_SafetyErrorCode_OTHER_INVERTER_IN_ERROR_38 = 38,
    vsr_MotorSafety_SafetyErrorCode_OVERSPEED_37 = 37,
    vsr_MotorSafety_SafetyErrorCode_PHASE_OVERCURRENT_17 = 17,
    vsr_MotorSafety_SafetyErrorCode_UNKNOWN_INTERNAL_ERROR_29 = 29,
    vsr_MotorSafety_SafetyErrorCode_UNKNOWN_TIMER_BREAK_ERROR_35 = 35,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_2_8 = 8,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_3_9 = 9,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_4_10 = 10,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_5_11 = 11,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_6_12 = 12,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_7_20 = 20,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_8_21 = 21,
    vsr_MotorSafety_SafetyErrorCode_UNUSED_ERROR_8_28 = 28,
    vsr_MotorSafety_SafetyErrorCode_WATCHDOG_RESET_34 = 34,
    vsr_MotorSafety_SafetyErrorCode_WRONG_HW_SETUP_27 = 27
} vsr_MotorSafety_SafetyErrorCode;

/* Struct definitions */
/* source key: accel_pedal
 alias: accel_pedal; Acceleration Pedal */
typedef struct _vsr_AccelPedal {
    /* Pedal Position as a percentage [%] */
    float pedal_position_pct;
    /* Pedal Raw ADC 1 */
    float pedal_raw_1;
    /* Pedal Raw ADC 2 */
    float pedal_raw_2;
    /* Pedal Supply Voltage [mV] */
    float pedal_supply_voltage;
} vsr_AccelPedal;

/* source key: brake_pedal
 alias: brake_pedal; The brakeline pressure sensor */
typedef struct _vsr_BrakePedal {
    /* Brake Position as a percent [TODO] [%] */
    float brake_position_pct;
    /* Brake Raw ADC 1 */
    float brake_raw_1;
    /* Pressure Sensor Supply Voltage [mV] */
    float brake_supply_voltage;
} vsr_BrakePedal;

typedef struct _vsr_DriveMode_CommandValue_CommandCruiseControl {
    uint32_t target_speed_rpm;
} vsr_DriveMode_CommandValue_CommandCruiseControl;

typedef struct _vsr_DriveMode_CommandValue_CommandDrive {
    char dummy_field;
} vsr_DriveMode_CommandValue_CommandDrive;

typedef struct _vsr_DriveMode_CommandValue_CommandNeutral {
    char dummy_field;
} vsr_DriveMode_CommandValue_CommandNeutral;

typedef struct _vsr_DriveMode_CommandValue_CommandPark {
    char dummy_field;
} vsr_DriveMode_CommandValue_CommandPark;

typedef struct _vsr_DriveMode_CommandValue_CommandReverse {
    char dummy_field;
} vsr_DriveMode_CommandValue_CommandReverse;

/* Vehicle Mode
 Tagged union for command */
typedef struct _vsr_DriveMode_CommandValue {
    pb_size_t which_kind;
    union {
        vsr_DriveMode_CommandValue_CommandPark park;
        vsr_DriveMode_CommandValue_CommandReverse reverse;
        vsr_DriveMode_CommandValue_CommandNeutral neutral;
        vsr_DriveMode_CommandValue_CommandDrive drive;
        vsr_DriveMode_CommandValue_CommandCruiseControl cruise_control;
    } kind;
} vsr_DriveMode_CommandValue;

/* source key: drive_mode
 alias: drive_mode */
typedef struct _vsr_DriveMode {
    bool has_command;
    vsr_DriveMode_CommandValue command;
} vsr_DriveMode;

/* source key: log
 alias: mcu_log; Log messages from the MCU */
typedef struct _vsr_Log {
    /* Log message from MCU */
    pb_size_t message_count;
    char message[16][128];
} vsr_Log;

/* source key: mcu_health
 alias: mcu_health; Basic MCU health telemetry */
typedef struct _vsr_McuHealth {
    /* Estimated total CPU load across both cores [%] */
    float cpu_load_pct;
    /* Current free heap [B] */
    uint32_t free_heap_bytes;
    /* Estimated used heap percentage [%] */
    float heap_used_pct;
    /* Minimum free heap since boot [B] */
    uint32_t min_free_heap_bytes;
    /* Current FreeRTOS task count */
    uint32_t task_count;
    /* Seconds since boot [s] */
    uint32_t uptime_s;
} vsr_McuHealth;

/* source key: motor_control
 alias: motor_control */
typedef struct _vsr_MotorControl {
    /* Charge Limit [%] */
    uint32_t charge_limit_pct;
    /* Current Reference [Arms] */
    int32_t current_reference;
    /* Discharge Limit [%] */
    uint32_t discharge_limit_pct;
} vsr_MotorControl;

/* source key: motor_error_state
 alias: motor_error */
typedef struct _vsr_MotorErrorState {
    vsr_MotorErrorState_MotorState motor_state;
} vsr_MotorErrorState;

/* source key: motor_power
 alias: motor_mspeed_status; Medium Speed motor status output */
typedef struct _vsr_MotorPower {
    /* Calculated DC Current [A] */
    float calculated_dc_current_a;
    /* DC Bus Voltage [V] */
    float measured_dc_voltage_v;
    /* Motor Current Limit [A] */
    float motor_current_limit_arms;
} vsr_MotorPower;

/* source key: motor_protections_1
 alias: motor_prot1 */
typedef struct _vsr_MotorProtections1 {
    /* CAN Timeout [ms] */
    uint32_t can_timeout_ms;
    /* DC Regen Current Limit [A] */
    uint32_t dc_regen_current_limit_neg_a;
    /* DC Traction Current Limit [A] */
    uint32_t dc_traction_current_limit_a;
    /* Overspeed Protection Speed (x10) [RPM] */
    uint32_t overspeed_protection_speed_rpm;
    /* Stall Protection Current [A] */
    uint32_t stall_protection_current_a;
    /* Stall Protection Time [ms] */
    uint32_t stall_protection_time_ms;
    /* Stall Protection Type */
    uint32_t stall_protection_type;
} vsr_MotorProtections1;

/* source key: motor_protections_2
 alias: motor_prot2 */
typedef struct _vsr_MotorProtections2 {
    /* Id Overcurrent Limit [A] */
    uint32_t id_overcurrent_limit_a;
    /* Inverter Temp High Gain [A/C] */
    uint32_t inverter_temp_high_gain_a_per_c;
    /* Max Inverter Temp [C] */
    uint32_t max_inverter_temp_c;
    /* Max Motor Temp [C] */
    uint32_t max_motor_temp_c;
    /* Motor Temp High Gain [A/C] */
    uint32_t motor_temp_high_gain_a_per_c;
    /* Overvoltage Limit [V] */
    uint32_t overvoltage_limit_v;
    /* Shutdown Voltage Limit [V] */
    uint32_t shutdown_voltage_limit_v;
} vsr_MotorProtections2;

/* source key: motor_safety
 alias: motor_lowspeed_safety; Low Speed Motor Output (safety) */
typedef struct _vsr_MotorSafety {
    /* Bus Capacitor Temperature [F] */
    int32_t bus_cap_temp;
    /* Inverter Bridge Temperature [F] */
    int32_t inverter_bridge_temp;
    /* Motor Temperature [F] */
    int32_t motor_temp;
    vsr_MotorSafety_ProtectionCode protection_code;
    /* PWM Status */
    uint32_t pwm_status;
    vsr_MotorSafety_SafetyErrorCode safety_error_code;
} vsr_MotorSafety;

/* source key: motor_speed
 alias: motor_highspeed_status; High speed (200 Hz) motor data */
typedef struct _vsr_MotorSpeed {
    /* Direct Current [Arms] */
    float direct_current;
    /* Motor Speed [RPM] */
    int32_t motor_speed;
    /* Quadrature Current [Arms] */
    float quadrature_current;
} vsr_MotorSpeed;

typedef struct _vsr_VehicleStatusRegister {
    /* alias: accel_pedal; Acceleration Pedal */
    bool has_accel_pedal;
    vsr_AccelPedal accel_pedal;
    /* alias: brake_pedal; The brakeline pressure sensor */
    bool has_brake_pedal;
    vsr_BrakePedal brake_pedal;
    /* alias: drive_mode */
    bool has_drive_mode;
    vsr_DriveMode drive_mode;
    /* alias: mcu_log; Log messages from the MCU */
    bool has_log;
    vsr_Log log;
    /* alias: mcu_health; Basic MCU health telemetry */
    bool has_mcu_health;
    vsr_McuHealth mcu_health;
    /* alias: motor_control */
    bool has_motor_control;
    vsr_MotorControl motor_control;
    /* alias: motor_error */
    bool has_motor_error_state;
    vsr_MotorErrorState motor_error_state;
    /* alias: motor_mspeed_status; Medium Speed motor status output */
    bool has_motor_power;
    vsr_MotorPower motor_power;
    /* alias: motor_prot1 */
    bool has_motor_protections_1;
    vsr_MotorProtections1 motor_protections_1;
    /* alias: motor_prot2 */
    bool has_motor_protections_2;
    vsr_MotorProtections2 motor_protections_2;
    /* alias: motor_lowspeed_safety; Low Speed Motor Output (safety) */
    bool has_motor_safety;
    vsr_MotorSafety motor_safety;
    /* alias: motor_highspeed_status; High speed (200 Hz) motor data */
    bool has_motor_speed;
    vsr_MotorSpeed motor_speed;
} vsr_VehicleStatusRegister;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _vsr_MotorErrorState_MotorState_MIN vsr_MotorErrorState_MotorState_MOTOR_OK
#define _vsr_MotorErrorState_MotorState_MAX vsr_MotorErrorState_MotorState_MOTOR_ERROR_STOP
#define _vsr_MotorErrorState_MotorState_ARRAYSIZE ((vsr_MotorErrorState_MotorState)(vsr_MotorErrorState_MotorState_MOTOR_ERROR_STOP+1))

#define _vsr_MotorSafety_ProtectionCode_MIN vsr_MotorSafety_ProtectionCode_NO_PROTECTIONS_ACTIVE_0
#define _vsr_MotorSafety_ProtectionCode_MAX vsr_MotorSafety_ProtectionCode_IQ_DECREASED_FIELD_WEAKENING_12
#define _vsr_MotorSafety_ProtectionCode_ARRAYSIZE ((vsr_MotorSafety_ProtectionCode)(vsr_MotorSafety_ProtectionCode_IQ_DECREASED_FIELD_WEAKENING_12+1))

#define _vsr_MotorSafety_SafetyErrorCode_MIN vsr_MotorSafety_SafetyErrorCode_NO_ERROR_0
#define _vsr_MotorSafety_SafetyErrorCode_MAX vsr_MotorSafety_SafetyErrorCode_OTHER_INVERTER_IN_ERROR_38
#define _vsr_MotorSafety_SafetyErrorCode_ARRAYSIZE ((vsr_MotorSafety_SafetyErrorCode)(vsr_MotorSafety_SafetyErrorCode_OTHER_INVERTER_IN_ERROR_38+1))













#define vsr_MotorErrorState_motor_state_ENUMTYPE vsr_MotorErrorState_MotorState




#define vsr_MotorSafety_protection_code_ENUMTYPE vsr_MotorSafety_ProtectionCode
#define vsr_MotorSafety_safety_error_code_ENUMTYPE vsr_MotorSafety_SafetyErrorCode




/* Initializer values for message structs */
#define vsr_AccelPedal_init_default              {0, 0, 0, 0}
#define vsr_BrakePedal_init_default              {0, 0, 0}
#define vsr_DriveMode_init_default               {false, vsr_DriveMode_CommandValue_init_default}
#define vsr_DriveMode_CommandValue_init_default  {0, {vsr_DriveMode_CommandValue_CommandPark_init_default}}
#define vsr_DriveMode_CommandValue_CommandCruiseControl_init_default {0}
#define vsr_DriveMode_CommandValue_CommandDrive_init_default {0}
#define vsr_DriveMode_CommandValue_CommandNeutral_init_default {0}
#define vsr_DriveMode_CommandValue_CommandPark_init_default {0}
#define vsr_DriveMode_CommandValue_CommandReverse_init_default {0}
#define vsr_Log_init_default                     {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define vsr_McuHealth_init_default               {0, 0, 0, 0, 0, 0}
#define vsr_MotorControl_init_default            {0, 0, 0}
#define vsr_MotorErrorState_init_default         {_vsr_MotorErrorState_MotorState_MIN}
#define vsr_MotorPower_init_default              {0, 0, 0}
#define vsr_MotorProtections1_init_default       {0, 0, 0, 0, 0, 0, 0}
#define vsr_MotorProtections2_init_default       {0, 0, 0, 0, 0, 0, 0}
#define vsr_MotorSafety_init_default             {0, 0, 0, _vsr_MotorSafety_ProtectionCode_MIN, 0, _vsr_MotorSafety_SafetyErrorCode_MIN}
#define vsr_MotorSpeed_init_default              {0, 0, 0}
#define vsr_VehicleStatusRegister_init_default   {false, vsr_AccelPedal_init_default, false, vsr_BrakePedal_init_default, false, vsr_DriveMode_init_default, false, vsr_Log_init_default, false, vsr_McuHealth_init_default, false, vsr_MotorControl_init_default, false, vsr_MotorErrorState_init_default, false, vsr_MotorPower_init_default, false, vsr_MotorProtections1_init_default, false, vsr_MotorProtections2_init_default, false, vsr_MotorSafety_init_default, false, vsr_MotorSpeed_init_default}
#define vsr_AccelPedal_init_zero                 {0, 0, 0, 0}
#define vsr_BrakePedal_init_zero                 {0, 0, 0}
#define vsr_DriveMode_init_zero                  {false, vsr_DriveMode_CommandValue_init_zero}
#define vsr_DriveMode_CommandValue_init_zero     {0, {vsr_DriveMode_CommandValue_CommandPark_init_zero}}
#define vsr_DriveMode_CommandValue_CommandCruiseControl_init_zero {0}
#define vsr_DriveMode_CommandValue_CommandDrive_init_zero {0}
#define vsr_DriveMode_CommandValue_CommandNeutral_init_zero {0}
#define vsr_DriveMode_CommandValue_CommandPark_init_zero {0}
#define vsr_DriveMode_CommandValue_CommandReverse_init_zero {0}
#define vsr_Log_init_zero                        {0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define vsr_McuHealth_init_zero                  {0, 0, 0, 0, 0, 0}
#define vsr_MotorControl_init_zero               {0, 0, 0}
#define vsr_MotorErrorState_init_zero            {_vsr_MotorErrorState_MotorState_MIN}
#define vsr_MotorPower_init_zero                 {0, 0, 0}
#define vsr_MotorProtections1_init_zero          {0, 0, 0, 0, 0, 0, 0}
#define vsr_MotorProtections2_init_zero          {0, 0, 0, 0, 0, 0, 0}
#define vsr_MotorSafety_init_zero                {0, 0, 0, _vsr_MotorSafety_ProtectionCode_MIN, 0, _vsr_MotorSafety_SafetyErrorCode_MIN}
#define vsr_MotorSpeed_init_zero                 {0, 0, 0}
#define vsr_VehicleStatusRegister_init_zero      {false, vsr_AccelPedal_init_zero, false, vsr_BrakePedal_init_zero, false, vsr_DriveMode_init_zero, false, vsr_Log_init_zero, false, vsr_McuHealth_init_zero, false, vsr_MotorControl_init_zero, false, vsr_MotorErrorState_init_zero, false, vsr_MotorPower_init_zero, false, vsr_MotorProtections1_init_zero, false, vsr_MotorProtections2_init_zero, false, vsr_MotorSafety_init_zero, false, vsr_MotorSpeed_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define vsr_AccelPedal_pedal_position_pct_tag    1
#define vsr_AccelPedal_pedal_raw_1_tag           2
#define vsr_AccelPedal_pedal_raw_2_tag           3
#define vsr_AccelPedal_pedal_supply_voltage_tag  4
#define vsr_BrakePedal_brake_position_pct_tag    1
#define vsr_BrakePedal_brake_raw_1_tag           2
#define vsr_BrakePedal_brake_supply_voltage_tag  3
#define vsr_DriveMode_CommandValue_CommandCruiseControl_target_speed_rpm_tag 1
#define vsr_DriveMode_CommandValue_park_tag      1
#define vsr_DriveMode_CommandValue_reverse_tag   2
#define vsr_DriveMode_CommandValue_neutral_tag   3
#define vsr_DriveMode_CommandValue_drive_tag     4
#define vsr_DriveMode_CommandValue_cruise_control_tag 5
#define vsr_DriveMode_command_tag                1
#define vsr_Log_message_tag                      1
#define vsr_McuHealth_cpu_load_pct_tag           1
#define vsr_McuHealth_free_heap_bytes_tag        2
#define vsr_McuHealth_heap_used_pct_tag          3
#define vsr_McuHealth_min_free_heap_bytes_tag    4
#define vsr_McuHealth_task_count_tag             5
#define vsr_McuHealth_uptime_s_tag               6
#define vsr_MotorControl_charge_limit_pct_tag    1
#define vsr_MotorControl_current_reference_tag   2
#define vsr_MotorControl_discharge_limit_pct_tag 3
#define vsr_MotorErrorState_motor_state_tag      1
#define vsr_MotorPower_calculated_dc_current_a_tag 1
#define vsr_MotorPower_measured_dc_voltage_v_tag 2
#define vsr_MotorPower_motor_current_limit_arms_tag 3
#define vsr_MotorProtections1_can_timeout_ms_tag 1
#define vsr_MotorProtections1_dc_regen_current_limit_neg_a_tag 2
#define vsr_MotorProtections1_dc_traction_current_limit_a_tag 3
#define vsr_MotorProtections1_overspeed_protection_speed_rpm_tag 4
#define vsr_MotorProtections1_stall_protection_current_a_tag 5
#define vsr_MotorProtections1_stall_protection_time_ms_tag 6
#define vsr_MotorProtections1_stall_protection_type_tag 7
#define vsr_MotorProtections2_id_overcurrent_limit_a_tag 1
#define vsr_MotorProtections2_inverter_temp_high_gain_a_per_c_tag 2
#define vsr_MotorProtections2_max_inverter_temp_c_tag 3
#define vsr_MotorProtections2_max_motor_temp_c_tag 4
#define vsr_MotorProtections2_motor_temp_high_gain_a_per_c_tag 5
#define vsr_MotorProtections2_overvoltage_limit_v_tag 6
#define vsr_MotorProtections2_shutdown_voltage_limit_v_tag 7
#define vsr_MotorSafety_bus_cap_temp_tag         1
#define vsr_MotorSafety_inverter_bridge_temp_tag 2
#define vsr_MotorSafety_motor_temp_tag           3
#define vsr_MotorSafety_protection_code_tag      4
#define vsr_MotorSafety_pwm_status_tag           5
#define vsr_MotorSafety_safety_error_code_tag    6
#define vsr_MotorSpeed_direct_current_tag        1
#define vsr_MotorSpeed_motor_speed_tag           2
#define vsr_MotorSpeed_quadrature_current_tag    3
#define vsr_VehicleStatusRegister_accel_pedal_tag 1
#define vsr_VehicleStatusRegister_brake_pedal_tag 2
#define vsr_VehicleStatusRegister_drive_mode_tag 3
#define vsr_VehicleStatusRegister_log_tag        4
#define vsr_VehicleStatusRegister_mcu_health_tag 5
#define vsr_VehicleStatusRegister_motor_control_tag 6
#define vsr_VehicleStatusRegister_motor_error_state_tag 7
#define vsr_VehicleStatusRegister_motor_power_tag 8
#define vsr_VehicleStatusRegister_motor_protections_1_tag 9
#define vsr_VehicleStatusRegister_motor_protections_2_tag 10
#define vsr_VehicleStatusRegister_motor_safety_tag 11
#define vsr_VehicleStatusRegister_motor_speed_tag 12

/* Struct field encoding specification for nanopb */
#define vsr_AccelPedal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pedal_position_pct,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    pedal_raw_1,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    pedal_raw_2,       3) \
X(a, STATIC,   SINGULAR, FLOAT,    pedal_supply_voltage,   4)
#define vsr_AccelPedal_CALLBACK NULL
#define vsr_AccelPedal_DEFAULT NULL

#define vsr_BrakePedal_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    brake_position_pct,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    brake_raw_1,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    brake_supply_voltage,   3)
#define vsr_BrakePedal_CALLBACK NULL
#define vsr_BrakePedal_DEFAULT NULL

#define vsr_DriveMode_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           1)
#define vsr_DriveMode_CALLBACK NULL
#define vsr_DriveMode_DEFAULT NULL
#define vsr_DriveMode_command_MSGTYPE vsr_DriveMode_CommandValue

#define vsr_DriveMode_CommandValue_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,park,kind.park),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,reverse,kind.reverse),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,neutral,kind.neutral),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,drive,kind.drive),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,cruise_control,kind.cruise_control),   5)
#define vsr_DriveMode_CommandValue_CALLBACK NULL
#define vsr_DriveMode_CommandValue_DEFAULT NULL
#define vsr_DriveMode_CommandValue_kind_park_MSGTYPE vsr_DriveMode_CommandValue_CommandPark
#define vsr_DriveMode_CommandValue_kind_reverse_MSGTYPE vsr_DriveMode_CommandValue_CommandReverse
#define vsr_DriveMode_CommandValue_kind_neutral_MSGTYPE vsr_DriveMode_CommandValue_CommandNeutral
#define vsr_DriveMode_CommandValue_kind_drive_MSGTYPE vsr_DriveMode_CommandValue_CommandDrive
#define vsr_DriveMode_CommandValue_kind_cruise_control_MSGTYPE vsr_DriveMode_CommandValue_CommandCruiseControl

#define vsr_DriveMode_CommandValue_CommandCruiseControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   target_speed_rpm,   1)
#define vsr_DriveMode_CommandValue_CommandCruiseControl_CALLBACK NULL
#define vsr_DriveMode_CommandValue_CommandCruiseControl_DEFAULT NULL

#define vsr_DriveMode_CommandValue_CommandDrive_FIELDLIST(X, a) \

#define vsr_DriveMode_CommandValue_CommandDrive_CALLBACK NULL
#define vsr_DriveMode_CommandValue_CommandDrive_DEFAULT NULL

#define vsr_DriveMode_CommandValue_CommandNeutral_FIELDLIST(X, a) \

#define vsr_DriveMode_CommandValue_CommandNeutral_CALLBACK NULL
#define vsr_DriveMode_CommandValue_CommandNeutral_DEFAULT NULL

#define vsr_DriveMode_CommandValue_CommandPark_FIELDLIST(X, a) \

#define vsr_DriveMode_CommandValue_CommandPark_CALLBACK NULL
#define vsr_DriveMode_CommandValue_CommandPark_DEFAULT NULL

#define vsr_DriveMode_CommandValue_CommandReverse_FIELDLIST(X, a) \

#define vsr_DriveMode_CommandValue_CommandReverse_CALLBACK NULL
#define vsr_DriveMode_CommandValue_CommandReverse_DEFAULT NULL

#define vsr_Log_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, STRING,   message,           1)
#define vsr_Log_CALLBACK NULL
#define vsr_Log_DEFAULT NULL

#define vsr_McuHealth_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    cpu_load_pct,      1) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap_bytes,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    heap_used_pct,     3) \
X(a, STATIC,   SINGULAR, UINT32,   min_free_heap_bytes,   4) \
X(a, STATIC,   SINGULAR, UINT32,   task_count,        5) \
X(a, STATIC,   SINGULAR, UINT32,   uptime_s,          6)
#define vsr_McuHealth_CALLBACK NULL
#define vsr_McuHealth_DEFAULT NULL

#define vsr_MotorControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   charge_limit_pct,   1) \
X(a, STATIC,   SINGULAR, SINT32,   current_reference,   2) \
X(a, STATIC,   SINGULAR, UINT32,   discharge_limit_pct,   3)
#define vsr_MotorControl_CALLBACK NULL
#define vsr_MotorControl_DEFAULT NULL

#define vsr_MotorErrorState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    motor_state,       1)
#define vsr_MotorErrorState_CALLBACK NULL
#define vsr_MotorErrorState_DEFAULT NULL

#define vsr_MotorPower_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    calculated_dc_current_a,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    measured_dc_voltage_v,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    motor_current_limit_arms,   3)
#define vsr_MotorPower_CALLBACK NULL
#define vsr_MotorPower_DEFAULT NULL

#define vsr_MotorProtections1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   can_timeout_ms,    1) \
X(a, STATIC,   SINGULAR, UINT32,   dc_regen_current_limit_neg_a,   2) \
X(a, STATIC,   SINGULAR, UINT32,   dc_traction_current_limit_a,   3) \
X(a, STATIC,   SINGULAR, UINT32,   overspeed_protection_speed_rpm,   4) \
X(a, STATIC,   SINGULAR, UINT32,   stall_protection_current_a,   5) \
X(a, STATIC,   SINGULAR, UINT32,   stall_protection_time_ms,   6) \
X(a, STATIC,   SINGULAR, UINT32,   stall_protection_type,   7)
#define vsr_MotorProtections1_CALLBACK NULL
#define vsr_MotorProtections1_DEFAULT NULL

#define vsr_MotorProtections2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id_overcurrent_limit_a,   1) \
X(a, STATIC,   SINGULAR, UINT32,   inverter_temp_high_gain_a_per_c,   2) \
X(a, STATIC,   SINGULAR, UINT32,   max_inverter_temp_c,   3) \
X(a, STATIC,   SINGULAR, UINT32,   max_motor_temp_c,   4) \
X(a, STATIC,   SINGULAR, UINT32,   motor_temp_high_gain_a_per_c,   5) \
X(a, STATIC,   SINGULAR, UINT32,   overvoltage_limit_v,   6) \
X(a, STATIC,   SINGULAR, UINT32,   shutdown_voltage_limit_v,   7)
#define vsr_MotorProtections2_CALLBACK NULL
#define vsr_MotorProtections2_DEFAULT NULL

#define vsr_MotorSafety_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   bus_cap_temp,      1) \
X(a, STATIC,   SINGULAR, SINT32,   inverter_bridge_temp,   2) \
X(a, STATIC,   SINGULAR, SINT32,   motor_temp,        3) \
X(a, STATIC,   SINGULAR, UENUM,    protection_code,   4) \
X(a, STATIC,   SINGULAR, UINT32,   pwm_status,        5) \
X(a, STATIC,   SINGULAR, UENUM,    safety_error_code,   6)
#define vsr_MotorSafety_CALLBACK NULL
#define vsr_MotorSafety_DEFAULT NULL

#define vsr_MotorSpeed_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    direct_current,    1) \
X(a, STATIC,   SINGULAR, SINT32,   motor_speed,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    quadrature_current,   3)
#define vsr_MotorSpeed_CALLBACK NULL
#define vsr_MotorSpeed_DEFAULT NULL

#define vsr_VehicleStatusRegister_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  accel_pedal,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  brake_pedal,       2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  drive_mode,        3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  log,               4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mcu_health,        5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_control,     6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_error_state,   7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_power,       8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_protections_1,   9) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_protections_2,  10) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_safety,     11) \
X(a, STATIC,   OPTIONAL, MESSAGE,  motor_speed,      12)
#define vsr_VehicleStatusRegister_CALLBACK NULL
#define vsr_VehicleStatusRegister_DEFAULT NULL
#define vsr_VehicleStatusRegister_accel_pedal_MSGTYPE vsr_AccelPedal
#define vsr_VehicleStatusRegister_brake_pedal_MSGTYPE vsr_BrakePedal
#define vsr_VehicleStatusRegister_drive_mode_MSGTYPE vsr_DriveMode
#define vsr_VehicleStatusRegister_log_MSGTYPE vsr_Log
#define vsr_VehicleStatusRegister_mcu_health_MSGTYPE vsr_McuHealth
#define vsr_VehicleStatusRegister_motor_control_MSGTYPE vsr_MotorControl
#define vsr_VehicleStatusRegister_motor_error_state_MSGTYPE vsr_MotorErrorState
#define vsr_VehicleStatusRegister_motor_power_MSGTYPE vsr_MotorPower
#define vsr_VehicleStatusRegister_motor_protections_1_MSGTYPE vsr_MotorProtections1
#define vsr_VehicleStatusRegister_motor_protections_2_MSGTYPE vsr_MotorProtections2
#define vsr_VehicleStatusRegister_motor_safety_MSGTYPE vsr_MotorSafety
#define vsr_VehicleStatusRegister_motor_speed_MSGTYPE vsr_MotorSpeed

extern const pb_msgdesc_t vsr_AccelPedal_msg;
extern const pb_msgdesc_t vsr_BrakePedal_msg;
extern const pb_msgdesc_t vsr_DriveMode_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_CommandCruiseControl_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_CommandDrive_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_CommandNeutral_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_CommandPark_msg;
extern const pb_msgdesc_t vsr_DriveMode_CommandValue_CommandReverse_msg;
extern const pb_msgdesc_t vsr_Log_msg;
extern const pb_msgdesc_t vsr_McuHealth_msg;
extern const pb_msgdesc_t vsr_MotorControl_msg;
extern const pb_msgdesc_t vsr_MotorErrorState_msg;
extern const pb_msgdesc_t vsr_MotorPower_msg;
extern const pb_msgdesc_t vsr_MotorProtections1_msg;
extern const pb_msgdesc_t vsr_MotorProtections2_msg;
extern const pb_msgdesc_t vsr_MotorSafety_msg;
extern const pb_msgdesc_t vsr_MotorSpeed_msg;
extern const pb_msgdesc_t vsr_VehicleStatusRegister_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define vsr_AccelPedal_fields &vsr_AccelPedal_msg
#define vsr_BrakePedal_fields &vsr_BrakePedal_msg
#define vsr_DriveMode_fields &vsr_DriveMode_msg
#define vsr_DriveMode_CommandValue_fields &vsr_DriveMode_CommandValue_msg
#define vsr_DriveMode_CommandValue_CommandCruiseControl_fields &vsr_DriveMode_CommandValue_CommandCruiseControl_msg
#define vsr_DriveMode_CommandValue_CommandDrive_fields &vsr_DriveMode_CommandValue_CommandDrive_msg
#define vsr_DriveMode_CommandValue_CommandNeutral_fields &vsr_DriveMode_CommandValue_CommandNeutral_msg
#define vsr_DriveMode_CommandValue_CommandPark_fields &vsr_DriveMode_CommandValue_CommandPark_msg
#define vsr_DriveMode_CommandValue_CommandReverse_fields &vsr_DriveMode_CommandValue_CommandReverse_msg
#define vsr_Log_fields &vsr_Log_msg
#define vsr_McuHealth_fields &vsr_McuHealth_msg
#define vsr_MotorControl_fields &vsr_MotorControl_msg
#define vsr_MotorErrorState_fields &vsr_MotorErrorState_msg
#define vsr_MotorPower_fields &vsr_MotorPower_msg
#define vsr_MotorProtections1_fields &vsr_MotorProtections1_msg
#define vsr_MotorProtections2_fields &vsr_MotorProtections2_msg
#define vsr_MotorSafety_fields &vsr_MotorSafety_msg
#define vsr_MotorSpeed_fields &vsr_MotorSpeed_msg
#define vsr_VehicleStatusRegister_fields &vsr_VehicleStatusRegister_msg

/* Maximum encoded size of messages (where known) */
#define VSR_VSR_PB_H_MAX_SIZE                    vsr_VehicleStatusRegister_size
#define vsr_AccelPedal_size                      20
#define vsr_BrakePedal_size                      15
#define vsr_DriveMode_CommandValue_CommandCruiseControl_size 6
#define vsr_DriveMode_CommandValue_CommandDrive_size 0
#define vsr_DriveMode_CommandValue_CommandNeutral_size 0
#define vsr_DriveMode_CommandValue_CommandPark_size 0
#define vsr_DriveMode_CommandValue_CommandReverse_size 0
#define vsr_DriveMode_CommandValue_size          8
#define vsr_DriveMode_size                       10
#define vsr_Log_size                             2080
#define vsr_McuHealth_size                       34
#define vsr_MotorControl_size                    18
#define vsr_MotorErrorState_size                 2
#define vsr_MotorPower_size                      15
#define vsr_MotorProtections1_size               42
#define vsr_MotorProtections2_size               42
#define vsr_MotorSafety_size                     28
#define vsr_MotorSpeed_size                      16
#define vsr_VehicleStatusRegister_size           2347

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
