/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "vsr.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(vsr_AccelPedal, vsr_AccelPedal, AUTO)


PB_BIND(vsr_BrakePedal, vsr_BrakePedal, AUTO)


PB_BIND(vsr_DriveMode, vsr_DriveMode, AUTO)


PB_BIND(vsr_DriveMode_CommandValue, vsr_DriveMode_CommandValue, AUTO)


PB_BIND(vsr_DriveMode_CommandValue_CommandCruiseControl, vsr_DriveMode_CommandValue_CommandCruiseControl, AUTO)


PB_BIND(vsr_DriveMode_CommandValue_CommandDrive, vsr_DriveMode_CommandValue_CommandDrive, AUTO)


PB_BIND(vsr_DriveMode_CommandValue_CommandNeutral, vsr_DriveMode_CommandValue_CommandNeutral, AUTO)


PB_BIND(vsr_DriveMode_CommandValue_CommandPark, vsr_DriveMode_CommandValue_CommandPark, AUTO)


PB_BIND(vsr_DriveMode_CommandValue_CommandReverse, vsr_DriveMode_CommandValue_CommandReverse, AUTO)


PB_BIND(vsr_Log, vsr_Log, 2)


PB_BIND(vsr_McuHealth, vsr_McuHealth, AUTO)


PB_BIND(vsr_MotorControl, vsr_MotorControl, AUTO)


PB_BIND(vsr_MotorErrorState, vsr_MotorErrorState, AUTO)


PB_BIND(vsr_MotorPower, vsr_MotorPower, AUTO)


PB_BIND(vsr_MotorProtections1, vsr_MotorProtections1, AUTO)


PB_BIND(vsr_MotorProtections2, vsr_MotorProtections2, AUTO)


PB_BIND(vsr_MotorSafety, vsr_MotorSafety, AUTO)


PB_BIND(vsr_MotorSpeed, vsr_MotorSpeed, AUTO)


PB_BIND(vsr_VehicleStatusRegister, vsr_VehicleStatusRegister, 2)









