/**
 * Autogenerated VSR state implementation.
 * Uses nanopb-generated vsr_VehicleStatusRegister encode.
 */

#include "vsr_state.h"

#include <string.h>

#include "pb_encode.h"

vehicle_status_reg_t vsr_global = { 0 };

int vsr_init(vehicle_status_reg_t* vsr) {
    if (vsr == NULL) {
        return -1;
    }

    memset(vsr, 0, sizeof(*vsr));
    {
        const vsr_VehicleStatusRegister zero = vsr_VehicleStatusRegister_init_zero;
        vsr->wire = zero;
    }
    // Default motor command oneof to park at startup.
    vsr->wire.drive_mode.has_command = true;
    vsr->wire.drive_mode.command.which_kind = vsr_DriveMode_CommandValue_park_tag;

    vsr->accel_pedal_mutex = xSemaphoreCreateMutex();
    vsr->accel_pedal_updated_at_us = 0;

    vsr->brake_pedal_mutex = xSemaphoreCreateMutex();
    vsr->brake_pedal_updated_at_us = 0;

    vsr->drive_mode_mutex = xSemaphoreCreateMutex();
    vsr->drive_mode_updated_at_us = 0;

    vsr->log_mutex = xSemaphoreCreateMutex();
    vsr->log_updated_at_us = 0;

    vsr->mcu_health_mutex = xSemaphoreCreateMutex();
    vsr->mcu_health_updated_at_us = 0;

    vsr->motor_control_mutex = xSemaphoreCreateMutex();
    vsr->motor_control_updated_at_us = 0;

    vsr->motor_error_state_mutex = xSemaphoreCreateMutex();
    vsr->motor_error_state_updated_at_us = 0;

    vsr->motor_power_mutex = xSemaphoreCreateMutex();
    vsr->motor_power_updated_at_us = 0;

    vsr->motor_protections_1_mutex = xSemaphoreCreateMutex();
    vsr->motor_protections_1_updated_at_us = 0;

    vsr->motor_protections_2_mutex = xSemaphoreCreateMutex();
    vsr->motor_protections_2_updated_at_us = 0;

    vsr->motor_safety_mutex = xSemaphoreCreateMutex();
    vsr->motor_safety_updated_at_us = 0;

    vsr->motor_speed_mutex = xSemaphoreCreateMutex();
    vsr->motor_speed_updated_at_us = 0;

    return 0;
}

bool vsr_serialize(
    const vehicle_status_reg_t* vsr,
    uint8_t* out_buf,
    size_t out_capacity,
    size_t* out_len
) {
    if (vsr == NULL || out_buf == NULL || out_len == NULL) {
        return false;
    }

    vsr_VehicleStatusRegister snapshot = vsr_VehicleStatusRegister_init_zero;

    ACQ_REL_VSRSEM_R(vsr, accel_pedal, {
        snapshot.has_accel_pedal = true;
        snapshot.accel_pedal = vsr->wire.accel_pedal;
    });

    ACQ_REL_VSRSEM_R(vsr, brake_pedal, {
        snapshot.has_brake_pedal = true;
        snapshot.brake_pedal = vsr->wire.brake_pedal;
    });

    ACQ_REL_VSRSEM_R(vsr, drive_mode, {
        snapshot.has_drive_mode = true;
        snapshot.drive_mode = vsr->wire.drive_mode;
        snapshot.drive_mode.has_command = true;
    });

    ACQ_REL_VSRSEM_R(vsr, log, {
        snapshot.has_log = true;
        snapshot.log = vsr->wire.log;
    });

    ACQ_REL_VSRSEM_R(vsr, mcu_health, {
        snapshot.has_mcu_health = true;
        snapshot.mcu_health = vsr->wire.mcu_health;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_control, {
        snapshot.has_motor_control = true;
        snapshot.motor_control = vsr->wire.motor_control;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_error_state, {
        snapshot.has_motor_error_state = true;
        snapshot.motor_error_state = vsr->wire.motor_error_state;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_power, {
        snapshot.has_motor_power = true;
        snapshot.motor_power = vsr->wire.motor_power;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_protections_1, {
        snapshot.has_motor_protections_1 = true;
        snapshot.motor_protections_1 = vsr->wire.motor_protections_1;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_protections_2, {
        snapshot.has_motor_protections_2 = true;
        snapshot.motor_protections_2 = vsr->wire.motor_protections_2;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_safety, {
        snapshot.has_motor_safety = true;
        snapshot.motor_safety = vsr->wire.motor_safety;
    });

    ACQ_REL_VSRSEM_R(vsr, motor_speed, {
        snapshot.has_motor_speed = true;
        snapshot.motor_speed = vsr->wire.motor_speed;
    });

    pb_ostream_t stream = pb_ostream_from_buffer(out_buf, out_capacity);
    if (!pb_encode(&stream, vsr_VehicleStatusRegister_fields, &snapshot)) {
        return false;
    }

    *out_len = stream.bytes_written;
    return true;
}