/**
 * Autogenerated VSR state wrapper around nanopb wire structs.
 * Plain structs + helper macros + function declarations.
 */

#ifndef VSR_STATE_H
#define VSR_STATE_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "esp_timer.h"
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "vsr.pb.h" // Generated by nanopb from generated/vsr.proto

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    // Full wire-compatible payload.
    vsr_VehicleStatusRegister wire;

    // One lock/timestamp per top-level VSR section.
    SemaphoreHandle_t accel_pedal_mutex;
    int64_t accel_pedal_updated_at_us;
    SemaphoreHandle_t brake_pedal_mutex;
    int64_t brake_pedal_updated_at_us;
    SemaphoreHandle_t drive_mode_mutex;
    int64_t drive_mode_updated_at_us;
    SemaphoreHandle_t log_mutex;
    int64_t log_updated_at_us;
    SemaphoreHandle_t mcu_health_mutex;
    int64_t mcu_health_updated_at_us;
    SemaphoreHandle_t motor_control_mutex;
    int64_t motor_control_updated_at_us;
    SemaphoreHandle_t motor_error_state_mutex;
    int64_t motor_error_state_updated_at_us;
    SemaphoreHandle_t motor_power_mutex;
    int64_t motor_power_updated_at_us;
    SemaphoreHandle_t motor_protections_1_mutex;
    int64_t motor_protections_1_updated_at_us;
    SemaphoreHandle_t motor_protections_2_mutex;
    int64_t motor_protections_2_updated_at_us;
    SemaphoreHandle_t motor_safety_mutex;
    int64_t motor_safety_updated_at_us;
    SemaphoreHandle_t motor_speed_mutex;
    int64_t motor_speed_updated_at_us;
} vehicle_status_reg_t;

/**
 * Shorthand for code paths where the local pointer variable is named `vsr`.
 * Example: `VSR.motor_control.current_reference = 10;`
 */
#define VSR_DATA (vsr->wire)

/**
 * Lock one slot for read access (no timestamp update).
 * Example: ACQ_REL_VSRSEM_R(vsr, motor_control, { copy = vsr->wire.motor_control; });
 */
#define ACQ_REL_VSRSEM_R(vsr_ptr, slot_name, body)                     \
    do {                                                             \
        xSemaphoreTake((vsr_ptr)->slot_name##_mutex,                \
                       portMAX_DELAY);                               \
        body                                                         \
        xSemaphoreGive((vsr_ptr)->slot_name##_mutex);               \
    } while (0)

/**
 * Lock one slot for write access (updates per-slot timestamp).
 * Example: ACQ_REL_VSRSEM_W(vsr, motor_control, { vsr->wire.motor_control = v; });
 */
#define ACQ_REL_VSRSEM_W(vsr_ptr, slot_name, body)                     \
    do {                                                             \
        xSemaphoreTake((vsr_ptr)->slot_name##_mutex,                \
                       portMAX_DELAY);                               \
        body                                                         \
        (vsr_ptr)->slot_name##_updated_at_us =                      \
            esp_timer_get_time();                                    \
        xSemaphoreGive((vsr_ptr)->slot_name##_mutex);               \
    } while (0)

extern vehicle_status_reg_t vsr_global;
int vsr_init(vehicle_status_reg_t* vsr);

bool vsr_serialize(
    const vehicle_status_reg_t* vsr,
    uint8_t* out_buf,
    size_t out_capacity,
    size_t* out_len
);

#ifdef __cplusplus
}
#endif

#endif // VSR_STATE_H