plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

//This automates the Rinearn3DGraph dependency
def rinearnZipUrl = 'https://download.rinearn.com/archive/graph3d/rinearn_graph_3d_5_6_46_en.zip'
def rinearnJar = file('lib/RinearnGraph3D.jar')
def rinearnZip = layout.buildDirectory.file("/tmp/rinearn_graph_3d.zip").get().asFile

tasks.register('downloadRinearnGraph3D') {
    outputs.file(rinearnJar)
    onlyIf { !rinearnJar.exists() }

    doLast {
        rinearnZip.parentFile.mkdirs()
        project.ant.get(src: rinearnZipUrl, dest: rinearnZip, skipexisting: true)

        project.copy {
from(zipTree(rinearnZip)) {
    include '**/RinearnGraph3D.jar'
    eachFile { fcd -> fcd.path = fcd.name } // flatten nested folder from the zip
}
            into 'lib'
            includeEmptyDirs = false
        }
    }
}

tasks.named('compileJava') {
    dependsOn 'downloadRinearnGraph3D'
}

dependencies {
    // UI Stuff
    implementation 'com.formdev:flatlaf:3.3'
    implementation 'org.jfree:jfreechart:1.5.4'

    // CSV parser
    implementation 'org.apache.commons:commons-csv:1.14.1'

    //UART
    implementation("com.fazecast:jSerialComm:2.10.4")

    //RinearnGraph3D graphgi
    implementation files("lib/RinearnGraph3D.jar")
}

application {
    mainClass = 'MainApp'
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_22
}
