//! Sensor main module, generated by scripts/gen_rust_sensor.py
//! This file should be included in your main.rs and the init_sensor function should be called.

use embassy_executor::Spawner;
use embassy_time::{Duration, Timer};
use rtt_target::rprintln;

// Include bindgen definitions
#[allow(non_upper_case_globals, non_camel_case_types, non_snake_case)]
pub mod bindings {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}
use bindings::*; // Allow access to C functions and types

// --- Data Collectors ---
#[allow(unused_variables)]
fn collect_battery_V(cancel_frame_send: &mut bool) -> i32 {
    // rprintln!("collecting battery_V");
    0
}

#[allow(unused_variables)]
fn collect_motor_V(cancel_frame_send: &mut bool) -> i32 {
    // rprintln!("collecting motor_V");
    0
}

#[allow(unused_variables)]
fn collect_prechargeState(cancel_frame_send: &mut bool) -> i32 {
    // rprintln!("collecting prechargeState");
    prechargeState.Off
}

#[allow(unused_variables)]
fn collect_contactorState(cancel_frame_send: &mut bool) -> i32 {
    // rprintln!("collecting contactorState");
    prechargeState.Off
}

#[allow(unused_variables)]
fn collect_prechargeLatched(cancel_frame_send: &mut bool) -> i32 {
    // rprintln!("collecting prechargeLatched");
    0
}



// --- Frame Sender Tasks ---

#[embassy_executor::task]
async fn send_frame_0_task() {
    let mut ticker = embassy_time::Ticker::every(embassy_time::Duration::from_millis(100));
    loop {
        let mut temp_data: [u8; 8] = [0; 8];
        let mut curr_bit: i8 = 0;
        let mut send_frame = true;

        // Collect and pack data
        let data = collect_battery_V(&mut send_frame);
        if !send_frame { continue; } // Skip frame send if requested by a collector
        unsafe { pecan_pack(temp_data.as_mut_ptr(), &mut curr_bit, data, &myframes[0].dataInfo.add(0)); }
        let data = collect_motor_V(&mut send_frame);
        if !send_frame { continue; } // Skip frame send if requested by a collector
        unsafe { pecan_pack(temp_data.as_mut_ptr(), &mut curr_bit, data, &myframes[0].dataInfo.add(1)); }
        let data = collect_prechargeState(&mut send_frame);
        if !send_frame { continue; } // Skip frame send if requested by a collector
        unsafe { pecan_pack(temp_data.as_mut_ptr(), &mut curr_bit, data, &myframes[0].dataInfo.add(2)); }
        let data = collect_contactorState(&mut send_frame);
        if !send_frame { continue; } // Skip frame send if requested by a collector
        unsafe { pecan_pack(temp_data.as_mut_ptr(), &mut curr_bit, data, &myframes[0].dataInfo.add(3)); }
        let data = collect_prechargeLatched(&mut send_frame);
        if !send_frame { continue; } // Skip frame send if requested by a collector
        unsafe { pecan_pack(temp_data.as_mut_ptr(), &mut curr_bit, data, &myframes[0].dataInfo.add(4)); }

        // Send the packet
        if curr_bit > 0 {
            let mut data_packet: CANPacket = unsafe { core::mem::zeroed() };
            data_packet.extendedID = 1;
            data_packet.id = unsafe { combinedIDExtended(functionCodes_transmitData as u32, myId as u32, 0 as u32) };
            let data_size = ((7 + curr_bit) / 8) as i8;
            
            unsafe {
                writeData(&mut data_packet, temp_data.as_ptr() as *mut i8, data_size);
                sendPacket(&mut data_packet);
            }
        }

        ticker.next().await;
    }
}


// --- Command Handling ---



// --- Main Sensor Initialization ---
pub fn init_sensor(spawner: &Spawner) {
    rprintln!("Initializing sensor tasks for node {}...", myId);

    // Spawn sender tasks
    spawner.spawn(send_frame_0_task()).unwrap();\n
    // Initialize and spawn receiver task if there are commands
    
    
}
