; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[arduinoBase]
platform = atmelavr
board = uno
framework = arduino
; Need to specify build src filter when extending, should look something like below
; build_src_filter = +<vitals_node/sensor.cpp> +<common/> +<arch/arduino.cpp> +<arch/arduino.hpp>
lib_deps =
    arkhipenko/TaskScheduler @ 3.7.0
monitor_port = /dev/ttyACM0
upload_port = /dev/ttyACM0
build_src_filter = +<arduinoSched/>

[arduinoCANBase]
extends=arduinoBase
lib_deps = 
    ${arduinoBase.lib_deps}
    sandeepmistry/CAN @ 0.3.1
build_src_filter = ${arduinoBase.build_src_filter} +<pecan/> -<pecan/espSpecific.c> 

[arduinoSensorBase]
extends = arduinoCANBase
build_src_filter = ${arduinoCANBase.build_src_filter} +<sensors/common/>

[espBase]
; platform = espressif32@6.7.0
platform = espressif32@7.0.0
; since we have both c and cpp code, and the newest espressif version treats all warning (like passing a C flag to Cpp program)
; as an error, we need to force platformio to stop passing invalid flags (that in previous version raised warning, but were just ignored)
build_unflags =
    -Wno-old-style-declaration
    -fuse-cxa-atexit

; Supress Twai driver warning (-Wno-error)
build_flags =
    -Wno-error=cpp
    -Wno-error=old-style-declaration

#^^for until we switch to new twai driver. our current one is deprectated. this suppresses the error
framework = espidf
board = esp32dev
board_build.mcu = esp32 #consider add an E
#specifying build_src_filter is invalid for espidf framework. ESP-IDF requires having two CMAKE files (one at src level to link and whatnot , and another at proj level to name project, and specify path to IDF toolchain stuff)
#instead, we can specifiy board_build.cmake_extra_args (in extensions of this), and modify the CMAKE file at src level to interpet these args to include appropriate files
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0
monitor_speed = 115200
build_unflags = -fuse-cxa-atexit

[espSensorBase]
extends = espBase
board_build.cmake_extra_args = -DCMAKE_SENSOR_ESP_BUILD=ON
build_flags = ${espBase.build_flags} -DSENSOR_ESP_BUILD=ON

[env:mcu]
extends=espSensorBase
board_build.cmake_extra_args = ${espSensorBase.board_build.cmake_extra_args} -DSENS_DIR=pedalSensor -DCMAKE_MCU_ESP_BUILD=ON
build_flags = ${espSensorBase.build_flags} -DNODE_CONFIG=../pedalSensor/helper/myDefines.hpp
monitor_port = /dev/ttyUSB1
upload_port = /dev/ttyUSB1
lib_deps = 
    etlcpp/Embedded Template Library@^20.43.4
    nanopb/Nanopb @ 0.4.91

monitor_speed = 921600

###   paste sensor environments here. or not idrc

#pedal sensor is merged into mcu

[env:IMU]
extends=espSensorBase
board_build.cmake_extra_args = ${espSensorBase.board_build.cmake_extra_args} -DSENS_DIR=IMU
build_flags = ${espSensorBase.build_flags} -DNODE_CONFIG=../IMU/helper/myDefines.hpp
board_build.use_idf_component_manager = true

[env:powerDistribution]
extends=espSensorBase
board_build.cmake_extra_args = ${espSensorBase.board_build.cmake_extra_args} -DSENS_DIR=powerDistribution
build_flags = ${espSensorBase.build_flags} -DNODE_CONFIG=../powerDistribution/helper/myDefines.hpp

###   end sensor envs

[env:espListen]
extends=espBase
build_flags = ${espBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_ESP_LISTEN_BUILD=ON
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[RadioLibBase]
extends = espBase
platform = ${espBase.platform}
build_unflags = ${espBase.build_unflags}
build_flags = ${espBase.build_flags} -Wno-error=overloaded-virtual
framework = ${espBase.framework}
board = ${espBase.board}
board_build.mcu = ${espBase.board_build.mcu}
monitor_port = ${espBase.monitor_port}
upload_port = ${espBase.upload_port}
monitor_speed = ${espBase.monitor_speed}
lib_deps =
    jgromes/RadioLib@7.6.0

[env:freeVitals]
extends=RadioLibBase
board_build.cmake_extra_args = -DCMAKE_VITALS_ESP_BUILD=ON
build_flags = ${RadioLibBase.build_flags} -DVITALS_ESP_BUILD
lib_deps =
            ${RadioLibBase.lib_deps}
            lz4
monitor_port = /dev/ttyUSB1
upload_port = /dev/ttyUSB1

[env:telemTXBenchmark]
extends=RadioLibBase
build_flags = ${RadioLibBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_TELEM_TX_BENCHMARK=ON
lib_deps =
            ${RadioLibBase.lib_deps}
            lz4
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[env:telemRXMain]
extends=RadioLibBase
build_flags = ${RadioLibBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_TELEM_RX_MAIN=ON
lib_deps =
            ${RadioLibBase.lib_deps}
            lz4
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[env:telemRXBenchmark]
extends=RadioLibBase
build_flags = ${RadioLibBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_TELEM_RX_BENCHMARK=ON
lib_deps =
            ${RadioLibBase.lib_deps}
            lz4
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[env:telemSimpleListen]
extends=RadioLibBase
build_flags = ${RadioLibBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_TELEM_Listen=ON
lib_deps = ${RadioLibBase.lib_deps}
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[env:telemSimpleTransmit]
extends=RadioLibBase
build_flags = ${RadioLibBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_TELEM_SIMPLE_TRANSMIT=ON
lib_deps = ${RadioLibBase.lib_deps}
monitor_port = /dev/ttyUSB0
upload_port = /dev/ttyUSB0

[env:bmsTest]
extends=espBase
build_flags = ${espBase.build_flags}
board_build.cmake_extra_args = -DCMAKE_BMS=ON
