alias = "motor_error"
desc = ""

[motor_state]
type = "enum"
unit = ""
desc = "High Level Motor State Enum"

  [motor_state.variants.MOTOR_OK]
    value = 0

  [motor_state.variants.MOTOR_ERROR_STOP]
    value = 1
