alias = "motor_command"
desc = ""

[command]
type = "enum"
unit = ""
desc = "Motor Command Mode"

  [command.variants.IDLE]
    value = 0

  [command.variants.REVERSE]
    value = 1

  [command.variants.DRIVE]
    value = 2

  [command.variants.CRUISECONTROL]
    value = 3
    target_speed_rpm = { type = "u16" }
