alias = "motor_prot2"
desc = ""

[max_motor_temp_c]
type = "u8"
unit = "C"
desc = "Max Motor Temp"

[motor_temp_high_gain_a_per_c]
type = "u8"
unit = "A/C"
desc = "Motor Temp High Gain"

[max_inverter_temp_c]
type = "u8"
unit = "C"
desc = "Max Inverter Temp"

[inverter_temp_high_gain_a_per_c]
type = "u8"
unit = "A/C"
desc = "Inverter Temp High Gain"

[id_overcurrent_limit_a]
type = "u16"
unit = "A"
desc = "Id Overcurrent Limit"

[overvoltage_limit_v]
type = "u16"
unit = "V"
desc = "Overvoltage Limit"

[shutdown_voltage_limit_v]
type = "u16"
unit = "V"
desc = "Shutdown Voltage Limit"
