//! Sensor-specific Rust module generated by scripts/gen_rust_sensor.py

use crate::sensor_specific;
use crate::ffi;
use crate::contactors;
use crate::imd;
use crate::vsense;
use embassy_executor::Spawner;

// --- Data Collectors ---
#[no_mangle]
pub extern "C" fn collect_battery_V(_cancel_frame_send: *mut bool) -> i32 {
    vsense::get_batteryvoltage() / 1000
}

#[no_mangle]
pub extern "C" fn collect_motor_V(_cancel_frame_send: *mut bool) -> i32 {
    vsense::get_motorvoltage() / 1000
}

#[no_mangle]
pub extern "C" fn collect_prechargeState(_cancel_frame_send: *mut bool) -> i32 {
    contactors::get_precharge_state()
}

#[no_mangle]
pub extern "C" fn collect_contactorState(_cancel_frame_send: *mut bool) -> i32 {
    contactors::get_contactor_state()
}

#[no_mangle]
pub extern "C" fn collect_IMD_frequency_Hz(_cancel_frame_send: *mut bool) -> i32 {
    imd::get_imd_frequency_hz()
}

#[no_mangle]
pub extern "C" fn collect_IMD_Duty_Cycle_Percent(_cancel_frame_send: *mut bool) -> i32 {
    imd::get_imd_duty_cycle_percent()
}

#[no_mangle]
pub extern "C" fn collect_IMD_Hardware_Fault_Indicator(_cancel_frame_send: *mut bool) -> i32 {
    imd::get_imd_hardware_fault_indicator()
}

#[no_mangle]
pub extern "C" fn collect_min_MC_Voltage(_cancel_frame_send: *mut bool) -> i32 {
    contactors::get_min_mc_voltage() / 1000
}

#[no_mangle]
pub extern "C" fn collect_minPercentCharged(_cancel_frame_send: *mut bool) -> i32 {
    contactors::get_min_percent_charged()
}


// --- Command Handling ---
#[no_mangle]
pub extern "C" fn onsetChargeCondition(args: ffi::setChargeCondition_args_t) {
    contactors::set_charge_condition(args.min_MC_Voltage, args.minPercentCharged);
}

pub fn init_sensor(spawner: &Spawner, plpc: &mut ffi::PCANListenParamsCollection) {
    sensor_specific::sensor_init(spawner, plpc);
}
