//! Sensor-specific Rust module generated by scripts/gen_rust_sensor.py

use crate::sensor_specific;
use embassy_executor::Spawner;
use sensor_common::ffi::PCANListenParamsCollection;

// --- Data Collectors ---

// --- Command Handling ---

pub fn init_sensor(spawner: &Spawner, plpc: &mut PCANListenParamsCollection) {
    sensor_specific::sensor_init(spawner, plpc);
}
