//! Sensor-specific Rust module generated by scripts/gen_rust_sensor.py

use crate::sensor_specific;
use crate::ffi;
use embassy_executor::Spawner;

// --- Data Collectors ---

// --- Command Handling ---

pub fn init_sensor(spawner: &Spawner, plpc: &mut ffi::PCANListenParamsCollection) {
    sensor_specific::sensor_init(spawner, plpc);
}
