use crate::vsr_metadata::vsr_type;
use std::any::TypeId;

fn type_id_to_c(id: TypeId) -> &'static str {
    if id == TypeId::of::<u8>() { "uint8_t" }
    else if id == TypeId::of::<i8>() { "int8_t" }
    else if id == TypeId::of::<u16>() { "uint16_t" }
    else if id == TypeId::of::<i16>() { "int16_t" }
    else if id == TypeId::of::<u32>() { "uint32_t" }
    else if id == TypeId::of::<i32>() { "int32_t" }
    else if id == TypeId::of::<f32>() { "float" }
    else if id == TypeId::of::<u64>() { "uint64_t" }
    else if id == TypeId::of::<i64>() { "int64_t" }
    else if id == TypeId::of::<f64>() { "double" }
    else if id == TypeId::of::<bool>() { "bool" }
    else { "void" }
}

pub fn generate_c(vsr_metadata: &vsr_type) -> (String, String) {
    // 1. Subtype Struct Definitions (Header)
    let subtype_defs: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let fields = subtype.fields.iter().map(|&(name, type_id, units, desc)| {
            let c_type = type_id_to_c(type_id);
            let unit_str = if units.is_empty() { String::new() } else { format!(" ({})", units) };
            format!("    {} {}; // {}{}", c_type, name, desc, unit_str)
        }).collect::<Vec<_>>().join("\n");

        format!(
        r#"typedef struct __attribute__((packed)) {{ 
{}
}} {}_s;"#,
        fields,
        subtype.name
        )
    }).collect::<Vec<_>>().join("\n\n");

    // 2. Main Struct Fields (Header)
    let main_struct_fields: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let type_name = subtype.name;
        let field_name = subtype.alias.unwrap_or(type_name);
        format!(
        r#"    SemaphoreHandle_t {field_name}_mutex;
    int64_t {field_name}_timestamp;
    {type_name}_s {field_name};"#,
            field_name = field_name,
            type_name = type_name
        )
    }).collect::<Vec<_>>().join("\n\n");
    
    let main_struct_def = format!(
    r#"typedef struct {{ 
{}
}} vehicle_status_reg_s;"#,
    main_struct_fields
    );

    let has_motor_error_state = vsr_metadata
        .subtypes
        .iter()
        .any(|subtype| subtype.name == "motor_error_state");

    let mut compat_defs = Vec::new();
    for subtype in vsr_metadata.subtypes {
        compat_defs.push(format!("typedef {name}_s {name}_t;", name = subtype.name));
    }
    if has_motor_error_state {
        compat_defs.push("typedef enum { MOTOR_OK = 0, MOTOR_ERROR_STOP = 1 } high_level_motor_state;".to_string());
        compat_defs.push("typedef motor_error_state_s motor_error_state;".to_string());
    }
    let compat_defs = compat_defs.join("\n");

    // 3. Init Logic (Source)
    let init_logic: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let field_name = subtype.alias.unwrap_or(subtype.name);
        format!(
        r#"    static StaticSemaphore_t {field_name}_mutex_buf;
    vsr->{field_name}_mutex = xSemaphoreCreateMutexStatic(&{field_name}_mutex_buf);"#,
            field_name = field_name
        )
    }).collect::<Vec<_>>().join("\n");

    // 4. Pack Logic (Source)
    let pack_logic: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let type_name = subtype.name;
        let field_name = subtype.alias.unwrap_or(type_name);
        format!(
        r#"    ACQ_REL_VSRSEM_R({field_name}, {{ 
        memcpy(buffer + offset, (void*)&vsr->{field_name}, sizeof({type_name}_s));
    }}); 
    offset += sizeof({type_name}_s);"#,
            field_name = field_name,
            type_name = type_name
        )
    }).collect::<Vec<_>>().join("\n\n");

    // --- Assemble final strings using templates ---
    let version = vsr_metadata.version;

    let h_out = format!(
    r#"// This file is automatically generated by vsr_codegen.rs
// Do not edit manually.
// Autogen VSR version {version}

#ifndef VSR_AUTOGEN_H
#define VSR_AUTOGEN_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "esp_timer.h"

// Acquire and release a vsr subregister semaphore
#define ACQ_REL_VSRSEM_W(mutating_element, body)                  \
    xSemaphoreTake(vsr->mutating_element##_mutex, portMAX_DELAY); \
    vsr->mutating_element##_timestamp = esp_timer_get_time();     \
    body xSemaphoreGive(vsr->mutating_element##_mutex);

#define ACQ_REL_VSRSEM_R(mutating_element, body)                  \
    xSemaphoreTake(vsr->mutating_element##_mutex, portMAX_DELAY); \
    body xSemaphoreGive(vsr->mutating_element##_mutex);

{subtype_defs}

// Backward Compatibility

{compat_defs}

{main_struct_def}

extern volatile vehicle_status_reg_s vehicle_status_register;

int vsr_init(volatile vehicle_status_reg_s* vsr);
size_t vsr_pack(volatile vehicle_status_reg_s* vsr, uint8_t* buffer);

#endif // VSR_AUTOGEN_H
"#,
        version = version,
        subtype_defs = subtype_defs,
        compat_defs = compat_defs,
        main_struct_def = main_struct_def
    );

    let c_out = format!(
    r##"#include "vsr.h"
#include <string.h>
#include "esp_timer.h"

volatile vehicle_status_reg_s vehicle_status_register = {{0}};

int vsr_init(volatile vehicle_status_reg_s* vsr) {{ 
    if (vsr == NULL) return -1;
    memset((void*)vsr, 0, sizeof(vehicle_status_reg_s));

{init_logic}

    return 0;
}}

size_t vsr_pack(volatile vehicle_status_reg_s* vsr, uint8_t* buffer) {{ 
    if (vsr == NULL || buffer == NULL) return 0;
    size_t offset = 0;

{pack_logic}
    return offset;
}}
"##,
        init_logic = init_logic,
        pack_logic = pack_logic
    );

    (h_out, c_out)
}
