use crate::vsr_metadata::vsr_type;
use std::any::TypeId;

fn type_id_to_c(id: TypeId) -> &'static str {
    if id == TypeId::of::<u8>() { "uint8_t" }
    else if id == TypeId::of::<i8>() { "int8_t" }
    else if id == TypeId::of::<u16>() { "uint16_t" }
    else if id == TypeId::of::<i16>() { "int16_t" }
    else if id == TypeId::of::<u32>() { "uint32_t" }
    else if id == TypeId::of::<i32>() { "int32_t" }
    else if id == TypeId::of::<f32>() { "float" }
    else if id == TypeId::of::<u64>() { "uint64_t" }
    else if id == TypeId::of::<i64>() { "int64_t" }
    else if id == TypeId::of::<f64>() { "double" }
    else if id == TypeId::of::<bool>() { "bool" }
    else { "void" }
}

fn type_id_to_printf(id: TypeId) -> Option<(&'static str, &'static str)> {
    if id == TypeId::of::<u8>() { Some(("PRIu8", "uint8_t")) }
    else if id == TypeId::of::<i8>() { Some(("PRId8", "int8_t")) }
    else if id == TypeId::of::<u16>() { Some(("PRIu16", "uint16_t")) }
    else if id == TypeId::of::<i16>() { Some(("PRId16", "int16_t")) }
    else if id == TypeId::of::<u32>() { Some(("PRIu32", "uint32_t")) }
    else if id == TypeId::of::<i32>() { Some(("PRId32", "int32_t")) }
    else if id == TypeId::of::<u64>() { Some(("PRIu64", "uint64_t")) }
    else if id == TypeId::of::<i64>() { Some(("PRId64", "int64_t")) }
    else { None }
}

pub fn generate_c(vsr_metadata: &vsr_type) -> (String, String) {
    // 1. Subtype Struct Definitions (Header)
    let subtype_defs: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let fields = subtype.fields.iter().map(|&(name, type_id, units, desc)| {
            let c_type = type_id_to_c(type_id);
            let unit_str = if units.is_empty() { String::new() } else { format!(" ({})", units) };
            format!("    {} {}; // {}{}", c_type, name, desc, unit_str)
        }).collect::<Vec<_>>().join("\n");

        format!(
        r#"typedef struct __attribute__((packed)) {{ 
{}
}} {}_s;"#,
        fields,
        subtype.name
        )
    }).collect::<Vec<_>>().join("\n\n");

    // 2. Main Struct Fields (Header)
    let main_struct_fields: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let type_name = subtype.name;
        let field_name = subtype.alias.unwrap_or(type_name);
        format!(
        r#"    SemaphoreHandle_t {field_name}_mutex;
    int64_t {field_name}_timestamp;
    {type_name}_s {field_name};"#,
            field_name = field_name,
            type_name = type_name
        )
    }).collect::<Vec<_>>().join("\n\n");
    
    let main_struct_def = format!(
    r#"typedef struct {{ 
{}
}} vehicle_status_reg_s;"#,
    main_struct_fields
    );

    let has_motor_error_state = vsr_metadata
        .subtypes
        .iter()
        .any(|subtype| subtype.name == "motor_error_state");

    let mut compat_defs = Vec::new();
    for subtype in vsr_metadata.subtypes {
        compat_defs.push(format!("typedef {name}_s {name}_t;", name = subtype.name));
    }
    if has_motor_error_state {
        compat_defs.push("typedef enum { MOTOR_OK = 0, MOTOR_ERROR_STOP = 1 } high_level_motor_state;".to_string());
        compat_defs.push("typedef motor_error_state_s motor_error_state;".to_string());
    }
    let compat_defs = compat_defs.join("\n");

    // 3. Init Logic (Source)
    let init_logic: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let field_name = subtype.alias.unwrap_or(subtype.name);
        format!(
        r#"    static StaticSemaphore_t {field_name}_mutex_buf;
    vsr->{field_name}_mutex = xSemaphoreCreateMutexStatic(&{field_name}_mutex_buf);"#,
            field_name = field_name
        )
    }).collect::<Vec<_>>().join("\n");

    // 4. Pack Logic (Source)
    let pack_logic: String = vsr_metadata.subtypes.iter().map(|subtype| {
        let type_name = subtype.name;
        let field_name = subtype.alias.unwrap_or(type_name);
        format!(
        r#"    ACQ_REL_VSRSEM_R({field_name}, {{ 
        memcpy(buffer + offset, (void*)&vsr->{field_name}, sizeof({type_name}_s));
    }}); 
    offset += sizeof({type_name}_s);"#,
            field_name = field_name,
            type_name = type_name
        )
    }).collect::<Vec<_>>().join("\n\n");

    // --- Assemble final strings using templates ---
    let version = vsr_metadata.version;

    let h_out = format!(
    r#"// This file is automatically generated by vsr_codegen.rs
// Do not edit manually.
// Autogen VSR version {version}

#ifndef VSR_AUTOGEN_H
#define VSR_AUTOGEN_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "freertos/FreeRTOS.h"
#include "freertos/semphr.h"
#include "esp_timer.h"

// Acquire and release a vsr subregister semaphore
#define ACQ_REL_VSRSEM_W(mutating_element, body)                  \
    xSemaphoreTake(vsr->mutating_element##_mutex, portMAX_DELAY); \
    vsr->mutating_element##_timestamp = esp_timer_get_time();     \
    body xSemaphoreGive(vsr->mutating_element##_mutex);

#define ACQ_REL_VSRSEM_R(mutating_element, body)                  \
    xSemaphoreTake(vsr->mutating_element##_mutex, portMAX_DELAY); \
    body xSemaphoreGive(vsr->mutating_element##_mutex);

{subtype_defs}

// Backward Compatibility

{compat_defs}

{main_struct_def}

extern volatile vehicle_status_reg_s vehicle_status_register;

int vsr_init(volatile vehicle_status_reg_s* vsr);
size_t vsr_pack(volatile vehicle_status_reg_s* vsr, uint8_t* buffer);

#endif // VSR_AUTOGEN_H
"#,
        version = version,
        subtype_defs = subtype_defs,
        compat_defs = compat_defs,
        main_struct_def = main_struct_def
    );

    let c_out = format!(
    r##"#include "vsr.h"
#include <string.h>
#include "esp_timer.h"

volatile vehicle_status_reg_s vehicle_status_register = {{0}};

int vsr_init(volatile vehicle_status_reg_s* vsr) {{ 
    if (vsr == NULL) return -1;
    memset((void*)vsr, 0, sizeof(vehicle_status_reg_s));

{init_logic}

    return 0;
}}

size_t vsr_pack(volatile vehicle_status_reg_s* vsr, uint8_t* buffer) {{ 
    if (vsr == NULL || buffer == NULL) return 0;
    size_t offset = 0;

{pack_logic}
    return offset;
}}
"##,
        init_logic = init_logic,
        pack_logic = pack_logic
    );

    (h_out, c_out)
}

pub fn generate_print(vsr_metadata: &vsr_type, vsr_header_include: &str) -> (String, String) {
    let has_motor_error_state = vsr_metadata
        .subtypes
        .iter()
        .any(|subtype| subtype.name == "motor_error_state");

    let print_functions: String = vsr_metadata
        .subtypes
        .iter()
        .map(|subtype| {
            let type_name = subtype.name;
            let field_name = subtype.alias.unwrap_or(type_name);
            let field_prints: String = subtype
                .fields
                .iter()
                .map(|&(field, type_id, units, _desc)| {
                    let label = if units.is_empty() {
                        field.to_string()
                    } else {
                        format!("{field} ({units})")
                    };
                    if type_name == "motor_error_state" && field == "motor_state" {
                        return format!(
                            "    printf(\"  {label}: %s (%d)\\n\", motor_state_to_str((high_level_motor_state) data.{field}), (int) data.{field});",
                            label = label,
                            field = field
                        );
                    }
                    if type_id == TypeId::of::<f32>() || type_id == TypeId::of::<f64>() {
                        return format!(
                            "    printf(\"  {label}: %.3f\\n\", (double) data.{field});",
                            label = label,
                            field = field
                        );
                    }
                    if type_id == TypeId::of::<bool>() {
                        return format!(
                            "    printf(\"  {label}: %s\\n\", data.{field} ? \"true\" : \"false\");",
                            label = label,
                            field = field
                        );
                    }
                    if let Some((fmt_macro, cast_type)) = type_id_to_printf(type_id) {
                        return format!(
                            "    printf(\"  {label}: %\" {fmt_macro} \"\\n\", ({cast_type}) data.{field});",
                            label = label,
                            fmt_macro = fmt_macro,
                            cast_type = cast_type,
                            field = field
                        );
                    }
                    format!("    // Unsupported field type for {field}", field = field)
                })
                .collect::<Vec<_>>()
                .join("\n");

            format!(
                r#"static void print_{field_name}(volatile vehicle_status_reg_s* vsr) {{
    {type_name}_s data;
    int64_t timestamp_us = 0;
    ACQ_REL_VSRSEM_R({field_name}, {{
        data = vsr->{field_name};
        timestamp_us = vsr->{field_name}_timestamp;
    }});
    printf("{field_name}:\n");
    print_timestamp_info("  ", timestamp_us);
{field_prints}
}}"#,
                field_name = field_name,
                type_name = type_name,
                field_prints = field_prints
            )
        })
        .collect::<Vec<_>>()
        .join("\n\n");

    let topics_table: String = vsr_metadata
        .subtypes
        .iter()
        .map(|subtype| {
            let field_name = subtype.alias.unwrap_or(subtype.name);
            format!(r#"    {{.name = "{field_name}", .print = &print_{field_name}}}"#, field_name = field_name)
        })
        .collect::<Vec<_>>()
        .join(",\n");

    let h_out = format!(
        r#"// This file is automatically generated by vsr_codegen.rs
// Do not edit manually.

#ifndef PRINT_VSR_H
#define PRINT_VSR_H

#include "{vsr_header_include}"
#include <stdbool.h>
#include <stddef.h>

typedef void (*vsr_print_function)(volatile vehicle_status_reg_s* vsr);

typedef struct {{
    const char* name;
    vsr_print_function print;
}} vsr_topic_printer_t;

const vsr_topic_printer_t* vsr_find_topic_printer(const char* name);
void vsr_print_topic(const vsr_topic_printer_t* topic, volatile vehicle_status_reg_s* vsr);
void vsr_print_all_topics(volatile vehicle_status_reg_s* vsr);
void vsr_print_available_topics(void);

#endif
"#,
        vsr_header_include = vsr_header_include
    );

    let c_out = format!(
        r#"// This file is automatically generated by vsr_codegen.rs
// Do not edit manually.

#include "print_vsr.h"

#include <inttypes.h>
#include <stdio.h>
#include <string.h>

#include "esp_timer.h"
#include "freertos/semphr.h"

static void print_timestamp_info(const char* indent, int64_t timestamp_us) {{
    int64_t age_ms = 0;
    if (timestamp_us > 0) {{
        int64_t now_us = esp_timer_get_time();
        if (now_us > timestamp_us) age_ms = (now_us - timestamp_us) / 1000;
    }}
    const char* note = timestamp_us > 0 ? "" : ", not updated yet";
    printf("%stimestamp: %" PRIi64 " us (%" PRIi64 " ms ago%s)\n", indent, timestamp_us, age_ms, note);
}}


{print_functions}

static const vsr_topic_printer_t kTopics[] = {{
{topics_table}
}};

const vsr_topic_printer_t* vsr_find_topic_printer(const char* name) {{
    if (!name) return NULL;
    for (size_t i = 0; i < sizeof(kTopics) / sizeof(kTopics[0]); ++i) {{
        if (strcmp(kTopics[i].name, name) == 0) return &kTopics[i];
    }}
    return NULL;
}}

void vsr_print_topic(const vsr_topic_printer_t* topic, volatile vehicle_status_reg_s* vsr) {{
    if (!topic || !vsr) return;
    topic->print(vsr);
}}

void vsr_print_all_topics(volatile vehicle_status_reg_s* vsr) {{
    if (!vsr) return;
    for (size_t i = 0; i < sizeof(kTopics) / sizeof(kTopics[0]); ++i) {{
        kTopics[i].print(vsr);
        if (i + 1 < sizeof(kTopics) / sizeof(kTopics[0])) puts("");
    }}
}}

void vsr_print_available_topics(void) {{
    printf("available topics:\n");
    for (size_t i = 0; i < sizeof(kTopics) / sizeof(kTopics[0]); ++i) {{
        printf("  %s\n", kTopics[i].name);
    }}
}}
"#,
        print_functions = print_functions,
        topics_table = topics_table
    );

    (h_out, c_out)
}
