import os
import shutil
from typing import Any, TextIO

from config.parseFile import ACCESS


def generate_rust_main(
    f: TextIO,
    node: list[dict[str, Any]],
    dataNames: list[str],
    has_commands: bool,
    sensor_commands: list[dict[str, Any]],
) -> None:
    collector_defs = ""
    current_data_idx = 0

    for frame in ACCESS(node, "CANFrames")["value"]:
        for dataPoint in ACCESS(frame, "dataInfo")["value"]:
            data_name = dataNames[current_data_idx]
            start_val = str(ACCESS(dataPoint, "startingValue")["value"])
            collector_defs += (
                "#[no_mangle]\n"
                f"pub extern \"C\" fn collect_{data_name}(_cancel_frame_send: *mut bool) -> i32 {{\n"
                f"    {start_val}\n"
                "}\n\n"
            )
            current_data_idx += 1

    command_defs = ""
    ffi_import = "use crate::ffi;\n" if has_commands else ""

    if has_commands:
        for cmd in sensor_commands:
            command_defs += (
                "#[no_mangle]\n"
                f"pub extern \"C\" fn on{cmd['name']}(_args: ffi::{cmd['name']}_args_t) {{\n"
                f"    // TODO: Implement logic for {cmd['name']}\n"
                "}\n\n"
            )

    content = f"""//! Sensor-specific Rust module generated by scripts/gen_rust_sensor.py

use crate::sensor_specific;
{ffi_import}use embassy_executor::Spawner;
use sensor_common::ffi::PCANListenParamsCollection;

// --- Data Collectors ---
{collector_defs}
// --- Command Handling ---
{command_defs}
pub fn init_sensor(spawner: &Spawner, plpc: &mut PCANListenParamsCollection) {{
    sensor_specific::sensor_init(spawner, plpc);
}}
"""
    f.write(content)


def generate_rust(
    node_name: str,
    sub_dir_path: str,
    helper_dir: str,
    base_dir: str,
    node: list[dict[str, Any]],
    data_names: list[str],
    has_commands: bool,
    sensor_commands: list[dict[str, Any]]
) -> None:
    """
    Generates the entire Cargo project structure and Rust-specific C-bindings.
    """
    cargo_name = node_name.lower().replace('_', '-')
    template_dir = os.path.join(base_dir, "codeBlocks", "rust")

    if not os.path.isdir(template_dir):
        print(f"Error: Rust common template dir not found at {template_dir}. Cannot generate '{node_name}'.")
        return

    # 1. Copy Cargo Templates
    common_files = {
        "build.rs": "build.rs",
        "memory.x": "memory.x",
        "Cargo.toml.template": "Cargo.toml",
        "Embed.toml": "Embed.toml",
        "main.rs.template": os.path.join("src", "main.rs"),
    }

    for src_rel, dest_rel in common_files.items():
        src_path = os.path.join(template_dir, src_rel)
        dest_path = os.path.join(sub_dir_path, dest_rel)

        if not os.path.exists(src_path):
            continue
        # Don't overwrite an existing main.rs so users can keep custom logic
        if dest_rel == os.path.join("src", "main.rs") and os.path.exists(dest_path):
            continue

        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        shutil.copy(src_path, dest_path)

    # 2. Customize Cargo.toml
    cargo_toml_path = os.path.join(sub_dir_path, "Cargo.toml")
    if os.path.exists(cargo_toml_path):
        with open(cargo_toml_path, 'r') as f:
            content = f.read()
        with open(cargo_toml_path, 'w') as f:
            f.write(content.replace("{{PACKAGE_NAME}}", cargo_name))

    # 3. Generate Rust-specific wrapper.h for Bindgen
    wrapper_path = os.path.join(helper_dir, 'wrapper.h')
    with open(wrapper_path, 'w') as f:
        f.write("// Wrapper header for bindgen, generated by scripts/genSensors.py\n\n")
        f.write("#include \"../../../src/programConstants.h\"\n")
        f.write("#include \"../../../src/sensors/common/sensorHelper.hpp\"\n")

    # 4. Generate sensor_main.rs
    src_dir = os.path.join(sub_dir_path, "src")
    os.makedirs(src_dir, exist_ok=True)
    main_path = os.path.join(src_dir, 'sensor_main.rs')
    
    with open(main_path, 'w') as f:
        generate_rust_main(f, node, data_names, has_commands, sensor_commands)
