from typing import Any, TextIO

from config.parseFile import ACCESS


def generate_rust_main(
    f: TextIO,
    node: list[dict[str, Any]],
    dataNames: list[str],
    numDataForNode: int,
    base_dir: str,
    has_commands: bool,
    sensor_commands: list[dict[str, Any]],
) -> None:
    collector_defs = ""
    current_data_idx = 0

    for frame in ACCESS(node, "CANFrames")["value"]:
        for dataPoint in ACCESS(frame, "dataInfo")["value"]:
            data_name = dataNames[current_data_idx]
            start_val = str(ACCESS(dataPoint, "startingValue")["value"])
            collector_defs += (
                "#[no_mangle]\n"
                f"pub extern \"C\" fn collect_{data_name}(_cancel_frame_send: *mut bool) -> i32 {{\n"
                f"    {start_val}\n"
                "}\n\n"
            )
            current_data_idx += 1

    command_defs = ""
    register_handlers_body = ""
    ffi_import = "use crate::ffi;\n"

    if has_commands:
        for cmd in sensor_commands:
            command_defs += (
                "#[no_mangle]\n"
                f"pub extern \"C\" fn on{cmd['name']}(_args: ffi::{cmd['name']}_args_t) {{\n"
                f"    // TODO: Implement logic for {cmd['name']}\n"
                "}\n\n"
            )
        register_handlers_body = "    ffi::registerCommandHandler(plpc);\n"
    else:
        register_handlers_body = "    let _ = plpc;\n"

    content = f"""//! Sensor-specific Rust module generated by scripts/gen_rust_sensor.py

use crate::sensor_specific;
{ffi_import}use embassy_executor::Spawner;

// --- Data Collectors ---
{collector_defs}
// --- Command Handling ---
{command_defs}unsafe fn register_sensor_command_handlers(plpc: *mut ffi::PCANListenParamsCollection) {{
{register_handlers_body}}}

pub fn init_sensor(spawner: &Spawner, plpc: &mut ffi::PCANListenParamsCollection) {{

    unsafe{{
        register_sensor_command_handlers(plpc as *mut ffi::PCANListenParamsCollection);
    }}
    sensor_specific::sensor_init(spawner, plpc);
}}
"""
    f.write(content)
