name: Check Code Formatting

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
          enable-cache: true

      - name: Install clang-format tool
        run: |
          uv tool install clang-format==21.1.2

          uv tool install rust-just==1.45.0

          echo "$(uv tool dir --bin)" >> "$GITHUB_PATH"

      - name: Check formatting
        run: |
          just check_format
